#' Summarize a Vegetation Index for each Growing Season
#' @description This function not only computes mean, median, and 90th percentile of a vegetation index (VI)
#' using observations for a user-specified "growing season," but also estimates the annual maximum VI and associated day of year
#' using phenology modeling and growing season observations.
#' @param dt Data.table generated by the function lsat_fit_phenologic_curves().
#' @param vi Character string specifying the vegetation index to summarize (e.g., NDVI).
#' @param min.frac.of.max Numeric threshold (0-1) that defines the "growing season" as the seasonal window when the
#' phenological curves indicate the VI is within a specified fraction of the maximum VI. In otherwords, an observation
#' is considered to be from the "growing season" when the VI is within a user-specified fraction of the curve-fit growing season maximum VI.
#' @param zscore.thresh Numeric threshold specifying the Z-score value beyond which individual observations are filtered before summarizing growing season VI.

#' @return Data.table summarizing annual growing season conditions based on a vegetation index.
#' @import data.table
#' @export lsat_summarize_growing_seasons
#'
#' @examples # Forthcoming...

lsat_summarize_growing_seasons = function(dt, vi, min.frac.of.max = 0.75, zscore.thresh = 3){
  dt <- data.table::data.table(dt)
  colnames(dt) <- gsub(vi, 'vi', colnames(dt))

  # take obervations from the 'growing season' identified as the period when vi typically exceedes a specified fraction of the typical max vi
  dt <- dt[spl.frac.max >= min.frac.of.max]

  # identify and filter out obs-level predictions of max VI that are anomalously high or low relative to other obs from that site x year
  dt <- dt[, ':='(avg = mean(vi.max.pred), sd = stats::sd(vi.max.pred), n=.N), by = c('sample.id','year')]
  dt <- dt[, abs.zscore := abs((vi.max.pred - avg )/sd)]
  dt <- dt[abs.zscore <= zscore.thresh]

  #  estimate max summer VI
  dt.smry <- dt[,.(latitude = data.table::first(latitude), longitude = data.table::first(longitude), n.obs = .N,
                   vi.gs.avg = mean(vi),
                   vi.gs.med = stats::median(vi),
                   vi.gs.q90 = stats::quantile(vi, 0.9),
                   vi.max = stats::median(vi.max.pred),
                   vi.max.lwr = min(vi.max.pred), vi.max.upr = max(vi.max.pred),
                   vi.max.doy = mean(spl.fit.max.doy)),
                by = c('sample.id','year')]

  # predicted max can't be lower than observed 90th pecentile
  dt.smry[vi.max < vi.gs.q90, vi.max := vi.gs.q90]

  #output
  colnames(dt.smry) <- gsub("vi", vi, colnames(dt.smry))
  dt.smry
}

